import type { MockUser } from "../types/auth";

export const mockUsers: MockUser[] = [
  {
    id: "USR-BANK-001",
    username: "bankadmin",
    password: "Bank@123",
    fullName: "Bank Administrator",
    email: "bankadmin@bank.demo",
    portal: "BANK_ADMIN",
    role: "BANK_ADMIN",
    isActive: true,
  },
  {
    id: "USR-PLATFORM-001",
    username: "platformadmin",
    password: "Platform@123",
    fullName: "Platform Administrator",
    email: "platformadmin@neobank.demo",
    portal: "PLATFORM_ADMIN",
    role: "PLATFORM_ADMIN",
    isActive: true,
  },
  {
    id: "USR-MERCHANT-001",
    username: "corporateadmin",
    password: "Corporate@123",
    fullName: "Aarav Mehta",
    email: "corporateadmin@acme.demo",
    portal: "MERCHANT",
    role: "CORPORATE_ADMIN",
    organisationId: "ORG-001",
    organisationName: "Acme Enterprises Private Limited",
    isActive: true,
  },
  {
    id: "USR-MERCHANT-002",
    username: "maker",
    password: "Maker@123",
    fullName: "Neha Sharma",
    email: "maker@acme.demo",
    portal: "MERCHANT",
    role: "MAKER",
    organisationId: "ORG-001",
    organisationName: "Acme Enterprises Private Limited",
    isActive: true,
  },
  {
    id: "USR-MERCHANT-003",
    username: "checker1",
    password: "Checker@123",
    fullName: "Rohan Verma",
    email: "checker1@acme.demo",
    portal: "MERCHANT",
    role: "CHECKER_LEVEL_1",
    organisationId: "ORG-001",
    organisationName: "Acme Enterprises Private Limited",
    isActive: true,
  },
  {
    id: "USR-MERCHANT-004",
    username: "checker2",
    password: "Checker@123",
    fullName: "Priya Nair",
    email: "checker2@acme.demo",
    portal: "MERCHANT",
    role: "CHECKER_LEVEL_2",
    organisationId: "ORG-001",
    organisationName: "Acme Enterprises Private Limited",
    isActive: true,
  },
  {
    id: "USR-MERCHANT-005",
    username: "viewer",
    password: "Viewer@123",
    fullName: "Karan Malhotra",
    email: "viewer@acme.demo",
    portal: "MERCHANT",
    role: "VIEW_ONLY",
    organisationId: "ORG-001",
    organisationName: "Acme Enterprises Private Limited",
    isActive: true,
  },
];
